# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 272b0ef40354868dee9b3815a1019e1be20c4d3dbe68625597037325e3181b2bc9c8ce0a951dd6c03ddbc54c7e84e03a7e38396a376e5323b16781e89173e815

test:
  secret_key_base: 82b990de75919507aabe8b615bb92228a26e4418357827c44c6e76d2d91d2cd7ac986c02400de1ac4059832f79d4dfdaaabc3d6804cdc6b7c41329631977aff2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
